debug: false
guisize: 27
guititle: '&eCoin Shop'
items:
  '1':
    slots:
      - 12
    amount: 1
    material: TRIPWIRE_HOOK
    glow: true
    name: "&8&l☂ {#00DDFB}&lT{#56EAFA}&lh{#ABF7F9}&lu{#B9F1F3}&ln{#80DAE8}&ld{#46C3DE}&le{#00DDFB}&lr {#56EAFA}&lK{#ABF7F9}&le{#B9F1F3}&ly &8&l☂"
    lore:
      - '&7Cost: {#8bf7f7}idk Coins'
    cost: 40
    commands:
      - givekeys %player% thunder 1
  '2':
    slots:
      - 13
    amount: 1
    material: TRIPWIRE_HOOK
    glow: true
    name: "{#001EFB}S{#0936FB}u{#124EFC}m{#1B67FC}m{#247FFD}e{#2C97FD}r {#35AFFE}K{#3EC8FE}e{#47E0FF}y{#50F8FF}!"
    lore:
      - '&7Cost: {#8bf7f7}idk Coins'
    cost: 40
    commands:
      - givekeys %player% summer2023 1
  '3':
    slots:
      - 14
    amount: 1
    material: TRIPWIRE_HOOK
    glow: true
    name: '&8&l☁ {#8BF7F7}Cloudy Crate Key &8&l☁'
    lore:
      - '&7Cost: {#8bf7f7}idk Coins'
    cost: 40
    commands:
      - givekeys %player% cloudy 1
  '4':
    slots:
      - 4
    amount: 1
    material: BOOK
    name: '&eYour current coins: %coins%'
    lore:
      - '&7Purchase more via /buy!'
  '5':
    slots:
      - 0
      - 1
      - 2
      - 3
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
    amount: 1
    material: BLACK_STAINED_GLASS_PANE
    name: ' '
  '6':
    slots:
      - 26
    amount: 1
    material: BARRIER
    name: '&cClose'
    closebutton: true
